###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "doc_identidad": 123,
  "nombres": "Javier Andres",
  "apellidos": "Sanchez Bohorquez",
  "email": "javier@email.com",
  "password": "contra123",
  "rol": "Administrador"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/ HTTP/1.1

###
DELETE http://localhost:9000/api/users/ HTTP/1.1

###
PUT http://localhost:9000/api/users/ HTTP/1.1
Content-Type: application/json

{
   "doc_identidad": 123,
  "nombres": "Javier Andres",
  "apellidos": "Sanchez Bohorquez",
  "email": "javier@email.com",
  "password": "contra123",
  "rol": "Administrador
}